<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="dates">
<xsd:complexType>
    <xsd:sequence>
        <xsd:element name="day"></xsd:element>
        <xsd:element name="month"></xsd:element>
    </xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:simpleType name="day">
    <xsd:restriction base="xsd:positiveInteger">
        <xsd:minInclusive value="1"></xsd:minInclusive>
        <xsd:maxInclusive value="31"></xsd:maxInclusive>
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="month">
    <xsd:restriction base="xsd:positiveInteger">
        <xsd:minInclusive value="1"></xsd:minInclusive>
        <xsd:maxInclusive value="12"></xsd:maxInclusive>
    </xsd:restriction>
</xsd:simpleType>

</xsd:schema>