<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aquarium">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nemos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nemo" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string"></xs:element>
                                        <xs:element name="prenom" type="xs:string"></xs:element>
                                        <xs:element name="specialite" type="xs:string"></xs:element>
                                        <xs:element name="age">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="0"></xs:minInclusive>
                                                    <xs:maxInclusive value="30"></xs:maxInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>